apiVersion: argoproj.io/v1alpha1
kind: RolloutManager
metadata:
  name: argo-rollouts
spec:
  plugins:
    metric:
      - name: argoproj-labs/metric-ai
        location: https://github.com/argoproj-labs/rollouts-plugin-metric-ai/releases/download/v0.0.1/rollouts-plugin-metric-ai-linux-amd64
        canary:
          analysis:
            startingStep: 1
            templates:
            - templateName: canary-analysis-ai-agent
          canaryMetadata:
            labels:
              role: canary
          stableMetadata:
            labels:
              role: stable